language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "nightly"
# command to install dependencies
install:
  - "pip install mock ."
# command to run tests
script: python prettyexc/tests.py
sudo: false
